# Codecov configuration for WaterBot
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 1%
        target: 80%
        base: auto
    patch:
      default:
        threshold: 1%
        target: 80%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "**/__init__.py"
  - "**/test_*.py"
  - "scripts/"
  - "image_builder/"
